### ISSUE TITLE
代码明显使用python3， 另外使用说明压根不管用

### ISSUE THREAD

**Issue by godvmxi** [talebook/talebook#133]
代码明显使用python3， 另外使用说明压根不管用。。。能否做的扎实点，想贡献都无门

**Comment by talebook** [comment]
首先感谢你对本项目的关注和支持，也欢迎提意见和建议。

本项目的前端是Vue框架，后端Tornado框架，后端环境的确是Python3。选择Python的原因是，
- 底层依赖的Calibre程序是python编写的
- 用python开发小项目也比较轻便

本项目最初开发时使用的是Python2，前一阵子才升级为Python3。由于是业余期间维护，主要开发者也只是我一个人，所以文档材料可能并不是很完善，难免有错漏。如果你有发现，欢迎提issue或者PR。

**Comment by talebook** [comment]
刚看了下 `document/INSTALL.zh_CN.md` 中的说明已经outdated了，我后续再更新一下。

如果你想搭建环境，推荐使用docker运行容器作为开发环境，然后将webserver代码目录挂载到/var/www/talebook/webserver目录即可。编写代码后，server会自动重启。可以参考这个docker-composer.yml
```
version: "2.4"

services:

  # main service
  dev:
    image: talebook/talebook
    volumes:
      - /data/dev:/data
      - /data/code/talebook/webserver:/var/www/talebook/webserver
    ports:
      - "8082:80"
    depends_on:
      - douban-rs-api

  # optional, for meta plugins
  # please set "http://douban-rs-api" in settings
  douban-rs-api:
    image: ghcr.io/cxfksword/douban-api-rs
```

手动搭建的话，可以参考下[talebook/calibre-docker项目中的Dockerfile](https://github.com/talebook/calibre-docker/blob/master/Dockerfile)，搭建出基础的calibre环境；然后再根据本仓库的Dockerfile中的RUN指令，安装nodejs和python的依赖。
