### ISSUE TITLE
书籍保存在哪里？如何备份？

### ISSUE THREAD

**Issue by huang5307** [talebook/talebook#303]
我是透过Compose来建立docker的，其中设定如下（我有一个共享文件夹 Resources，我在此文件下面建立一个子目录Calibre） ：
```
  talebook:
    restart: always
    image: talebook/talebook
    volumes:
      - /Resources/Calibre:/data
```
系统运行没有问题，我也上传了2本书上去，看似也没有问题。
<img width="928" alt="image" src="https://github.com/talebook/talebook/assets/7876228/0476b5b4-e679-4f10-930c-262aba570d46">
但问题是这2本书放在什么地方呢？因为我建立的目录  /Resources/Calibre 里面根本没有任何资料，我查了所有的目录也没有发现什么新的目录，那到底这本书放在什么地方呢？
<img width="275" alt="image" src="https://github.com/talebook/talebook/assets/7876228/9b37687e-4eaf-4392-8d8f-74546cce1efe">
